[project]
name = "project-double-double"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mooz-55", email = "cadenchandra@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
project-double-double = "project_double_double:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
